name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: check-jira-keys
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: Checking that all commit messages contain a Jira ID
          
      - name: report failure if all commit messages did not contain a Jira ID
        run: exit 1
